export const ACTIVITY_LABELS: Record<string, string> = {
  admin_login_success: 'Connexion admin',
  admin_logout: 'Déconnexion admin',
  admin_profile_updated: 'Profil admin mis à jour',
  admin_avatar_uploaded: 'Photo profil admin mise à jour',
  admin_password_changed: 'Mot de passe admin modifié',
  staff_created: 'Compte staff créé',
  staff_updated: 'Compte staff modifié',
  subscriber_registered: 'Inscription abonné',
  subscriber_login_success: 'Connexion abonné',
  subscriber_google_login: 'Connexion Google abonné',
  subscriber_logout: 'Déconnexion abonné',
  subscriber_profile_updated: 'Profil abonné mis à jour',
  subscriber_avatar_uploaded: 'Photo profil abonné mise à jour',
  subscriber_password_changed: 'Mot de passe abonné modifié',
  subscriber_password_reset_requested: 'Demande reset mot de passe abonné',
  subscriber_password_reset: 'Réinitialisation mot de passe abonné',
  subscriber_email_verified: 'Email abonné confirmé',
  subscriber_verification_resent: 'Renvoi confirmation email abonné',
  subscriber_updated: 'Abonné modifié',
  subscriber_blocked: 'Abonné bloqué',
  subscriber_unblocked: 'Abonné débloqué',

  magazine_created: 'Magazine créé',
  magazine_updated: 'Magazine modifié',
  magazine_cover_uploaded: 'Couverture magazine uploadée',
  magazine_pdf_uploaded: 'PDF magazine uploadé',
  magazine_pages_ensure: 'Génération pages demandée (admin)',
  magazine_pages_reprocess: 'Regénération pages demandée (admin)',
  magazine_pages_queued: 'Pages magazine mises en file',
  magazine_pages_started: 'Rasterisation pages démarrée',
  magazine_pages_ready: 'Pages magazine prêtes',
  magazine_pages_failed: 'Échec rasterisation pages',
  magazine_pages_recovered: 'Job pages orphelin repris',
  monitoring_alert_sent: 'Alerte monitoring envoyée',
  article_created: 'Actualité créée',
  article_updated: 'Actualité modifiée',
  article_cover_uploaded: 'Couverture actualité uploadée',
  payment_succeeded: 'Paiement réussi',
  payment_forced_success: 'Paiement forcé (assistance)',
  payment_status_updated: 'Statut paiement modifié',
  payment_status_otp_sent: 'OTP confirmation paiement envoyé',
  payment_checkout_started: 'Checkout Stripe démarré',
  payment_flexpaie_started: 'Paiement FlexPaie démarré',
  subscription_activated: 'Abonnement activé',
  subscription_updated: 'Abonnement modifié',
  plan_created: 'Formule créée',
  plan_updated: 'Formule modifiée',
};

export function labelActivityAction(action: string): string {
  return ACTIVITY_LABELS[action] ?? action;
}
