/** Référentiel pays legacy (`pays`) — nom → indicatif. */
export const COUNTRIES: { name: string; code: string }[] = [
  { name: "Afrique du Sud", code: "27" },
  { name: "Algérie", code: "213" },
  { name: "Allemagne", code: "49" },
  { name: "Angola", code: "244" },
  { name: "Argentine", code: "54" },
  { name: "Australie", code: "61" },
  { name: "Autriche", code: "43" },
  { name: "Belgique", code: "32" },
  { name: "Bénin", code: "229" },
  { name: "Brésil", code: "55" },
  { name: "Burkina Faso", code: "226" },
  { name: "Burundi", code: "257" },
  { name: "Cameroun", code: "237" },
  { name: "Canada", code: "1" },
  { name: "Chili", code: "56" },
  { name: "Chine", code: "86" },
  { name: "Congo", code: "242" },
  { name: "Côte d'Ivoire", code: "225" },
  { name: "Egypte", code: "20" },
  { name: "Espagne", code: "34" },
  { name: "Etats-unis Amérique", code: "1" },
  { name: "France", code: "33" },
  { name: "Gabon", code: "241" },
  { name: "Ghana", code: "233" },
  { name: "Italie", code: "39" },
  { name: "Kenya", code: "254" },
  { name: "Luxembourg", code: "352" },
  { name: "Madagascar", code: "261" },
  { name: "Mali", code: "223" },
  { name: "Maroc", code: "212" },
  { name: "Maurice", code: "230" },
  { name: "Niger", code: "227" },
  { name: "Nigeria", code: "234" },
  { name: "Pays-Bas", code: "31" },
  { name: "RD.Congo", code: "243" },
  { name: "Royaume-Uni", code: "44" },
  { name: "Rwanda", code: "250" },
  { name: "Sénégal", code: "221" },
  { name: "Suisse", code: "41" },
  { name: "Togo", code: "228" },
  { name: "Tunisie", code: "216" },
];
